kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: svenc56/discourse-teamspeak-bridge
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      tags:
        - latest
