kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: svenc56/discourse-teamspeak-bridge
      dockerfile: Dockerfile
      auto_tag: true
      auto_tag_suffix: alpine
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback
